import './globals.css'
import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
//Using Theme Provider form shadcn ui to make the application in dark mode
import { ThemeProvider } from '@/components/providers/theme-provider'
//using cn to change the color wether we re looking at the website from dark mode or light mode
import { cn } from '@/lib/utils'
const font = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Team Chat Application',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en"  suppressHydrationWarning>
        <body className={cn(
          font.className,
          "bg-white dark:bg-[#313338]"
          )}>

          <ThemeProvider
            attribute = "class"
              defaultTheme ="dark"
              enableSystem = {false}
              storageKey='discord-theme'
              >
            {children}
          
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
